### PR TITLE
rm compact helper

### PR DESCRIPTION
**Pull request by GiggleLiu**

### CODE REVIEW

**Comment by Roger-luo** [comment]
why?

**Comment by GiggleLiu** [comment]
It complaints GitHub action does not have the permission to make a pr. It seems the security strategy of the org has been changed.

**Comment by Roger-luo** [comment]
well, then we should fix it instead of removing it... you need it keep dependencies up to date, unless you are confident doing this manually

**Comment by GiggleLiu** [comment]
Thanks, just restored the CompactHelper file.

**Review by Roger-luo — APPROVED** [review]

**Pull request merged**
